# DB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# AWS
aws.region=${AWS_REGION}
# AWS S3 BUCKET
aws.s3.movie.poster.bucket.name=${AWS_S3_MOVIE_POSTER_BUCKET_NAME}
aws.s3.movie.poster.folder.name=${AWS_S3_MOVIE_POSTER_FOLDER_NAME}
aws.s3.movie.video.bucket.name=${AWS_S3_MOVIE_VIDEO_BUCKET_NAME}
aws.s3.movie.video.folder.name=${AWS_S3_MOVIE_VIDEO_FOLDER_NAME}
aws.credentials.access.key=${AWS_CREDENTIALS_ACCESS_KEY}
aws.credentials.secret.key=${AWS_CREDENTIALS_SECRET_KEY}
aws.s3.endpoint=${AWS_S3_ENDPOINT}
app.payment.provider.url=http://localhost:8080/api/v1/mock/payments/create-session
app.purchase.webhook.endpoint=/api/v1/lumen/purchases/callback