# DB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# AWS
aws.credentials.access.key=${AWS_CREDENTIALS_ACCESS_KEY}
aws.credentials.secret.key=${AWS_CREDENTIALS_SECRET_KEY}
aws.region=${AWS_REGION}
# AWS S3 BUCKET
aws.s3.movie.poster.bucket.name=${AWS_S3_MOVIE_POSTER_BUCKET_NAME}
aws.s3.movie.poster.folder.name=${AWS_S3_MOVIE_POSTER_FOLDER_NAME}
aws.s3.movie.video.bucket.name=${AWS_S3_MOVIE_VIDEO_BUCKET_NAME}
aws.s3.movie.video.folder.name=${AWS_S3_MOVIE_VIDEO_FOLDER_NAME}
aws.s3.endpoint=${AWS_S3_ENDPOINT}
# SES CONFIGURATION
aws.ses.endpoint=${AWS_SES_ENDPOINT}
# REPORT GENERATION CONFIGURATION
app.report.enabled=${APP_REPORT_ENABLED}
app.report.schedule.cron=${APP_REPORT_SCHEDULE_CRON}
app.report.formats=${APP_REPORT_FORMATS}
app.report.recipients=${APP_REPORT_RECIPIENTS}
app.report.sender=${APP_REPORT_SENDER}
app.report.period.duration=${APP_REPORT_PERIOD_DURATION:P4W}
# PURCHASE & PAYMENT CONFIGURATION
app.payment.provider.url=${APP_PAYMENT_PROVIDER_URL}
app.purchase.webhook.endpoint=${APP_PURCHASE_WEBHOOK_ENDPOINT}
