# DB
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
# AWS
aws.region=us-east-1
# AWS S3 BUCKET
aws.s3.movie.poster.bucket.name=test-movie-posters
aws.s3.movie.poster.folder.name=posters
aws.s3.movie.video.bucket.name=test-movie-videos
aws.s3.movie.video.folder.name=videos
